### ISSUE TITLE
regarding himalaya running

### ISSUE THREAD

**Issue by shrishti01** [andrejewski/himalaya#76] opened 2017-11-16 10:06 UTC
Please help me with how to start using this project.

Thanks & Regards

**Comment by andrejewski** [comment] 2017-11-16 21:47
The README has instructions for using Himalaya. I'm closing this issue as it is not a bug report or feature request. Please do not create more issues of this kind. Reach out to me via email with a full explanation of your problem if you are interested in getting direct assistance.

**Closed by andrejewski** 2017-11-16 21:47 UTC
